INSERT INTO "golden"."integrationsMaster" (
    "id", 
    "integrationName", 
    "applicationName",
    "integrationCode", 
    "logo", 
    "description", 
    "isFavorite",
    "integrationType", 
    "connectionType", 
    "authType",
    "connectionLimit", 
    "integrationCategory",
    "status", 
    "companyIds", 
    "tags", 
    "isTested", 
    "createdBy", 
    "syncToken"
) VALUES 
-- Microsoft Dynamics 365
(
    '00000000-0000-0000-0000-000000000001', 
    'Microsoft Dynamics 365', 
    'Microsoft Dynamics 365',
    'MS-DYN-365', 
    'https://www.solzit.com/wp-content/uploads/2024/09/Microsoft-Dynamics-365-logo.png', 
    'Enterprise resource planning (ERP) and customer relationship management (CRM) applications',
    TRUE, 
    'System', 
    'API', 
    'OAuth2',
    5, 
    'ERP',
    'Active', 
    ARRAY[]::UUID[], -- Replace with actual company IDs
    '["ERP", "CRM", "Microsoft"]', 
    TRUE, 
    'System', 
    uuid_generate_v4()
),
-- Office 365
(
    '00000000-0000-0000-0000-000000000002', 
    'Office 365', 
    'Office 365',
    'MS-O365', 
    'https://play-lh.googleusercontent.com/Cf6rGlvAZJx2iG4c5f5H5N5XWGKFk5XZ_uz0A0YIIyuFPFybIfQaxSlDIQyU2W8btfv6=w240-h480-rw', 
    'Productivity suite including email, document editing, and collaboration tools', 
    TRUE, 
    'System', 
    'API', 
    'OAuth2',
    3, 
    'Productivity',
    'Active', 
    ARRAY[]::UUID[], -- Replace with actual company IDs
    '["Productivity", "Microsoft", "Email", "Documents"]', 
    TRUE, 
    'System', 
    uuid_generate_v4()
),
-- Azure DevOps
(
    '00000000-0000-0000-0000-000000000003', 
    'Azure DevOps', 
    'Azure DevOps',
    'AZURE-DEVOPS', 
    'https://cdn.iconscout.com/icon/free/png-256/free-azure-devops-logo-icon-download-in-svg-png-gif-file-formats--technology-social-media-company-vol-1-pack-logos-icons-3029870.png?f=webp&w=256', 
    'Development collaboration tools including Git repositories, CI/CD pipelines, and agile boards', 
    FALSE, 
    'System', 
    'REST', 
    'APIKey',
    3, 
    'Project Management',
    'Inactive', 
    ARRAY[]::UUID[], -- Replace with actual company IDs
    '["DevOps", "Microsoft", "CI/CD"]', 
    FALSE, 
    'System', 
    uuid_generate_v4()
),
-- Salesforce
(
    '00000000-0000-0000-0000-000000000004', 
    'Salesforce', 
    'Salesforce',
    'SF-CRM', 
    'https://w7.pngwing.com/pngs/738/117/png-transparent-salesforce-com-cloud-computing-salesforce-marketing-cloud-sales-engineer-blue-text-logo-thumbnail.png', 
    'Customer relationship management (CRM) platform for sales, service, marketing, and more', 
    TRUE, 
    'System', 
    'API', 
    'PAT',
    4, 
    'CRM',
    'Active', 
    ARRAY[]::UUID[], -- Replace with actual company IDs
    '["CRM", "Sales", "Marketing"]', 
    TRUE, 
    'System', 
    uuid_generate_v4()
),
-- Slack
(
    '00000000-0000-0000-0000-000000000005', 
    'Slack', 
    'Slack',
    'SLACK', 
    'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/306_Slack_logo-512.png', 
    'Business communication platform offering many IRC-style features', 
    FALSE, 
    'System', 
    'REST', 
    'OAuth2',
    2, 
    'Communication',
    'Inactive', 
    ARRAY[]::UUID[], -- Replace with actual company IDs
    '["Communication", "Messaging", "Collaboration"]', 
    FALSE, 
    'System', 
    uuid_generate_v4()
);