create table "public"."moduleConfiguration" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "configuration" json,
    "createdOn" timestamp with time zone not null default now(),
    "updatedOn" timestamp with time zone
);


CREATE UNIQUE INDEX "moduleConfiguration_pkey" ON public."moduleConfiguration" USING btree (id);

alter table "public"."moduleConfiguration" add constraint "moduleConfiguration_pkey" PRIMARY KEY using index "moduleConfiguration_pkey";

grant delete on table "public"."moduleConfiguration" to "anon";

grant insert on table "public"."moduleConfiguration" to "anon";

grant references on table "public"."moduleConfiguration" to "anon";

grant select on table "public"."moduleConfiguration" to "anon";

grant trigger on table "public"."moduleConfiguration" to "anon";

grant truncate on table "public"."moduleConfiguration" to "anon";

grant update on table "public"."moduleConfiguration" to "anon";

grant delete on table "public"."moduleConfiguration" to "authenticated";

grant insert on table "public"."moduleConfiguration" to "authenticated";

grant references on table "public"."moduleConfiguration" to "authenticated";

grant select on table "public"."moduleConfiguration" to "authenticated";

grant trigger on table "public"."moduleConfiguration" to "authenticated";

grant truncate on table "public"."moduleConfiguration" to "authenticated";

grant update on table "public"."moduleConfiguration" to "authenticated";

grant delete on table "public"."moduleConfiguration" to "service_role";

grant insert on table "public"."moduleConfiguration" to "service_role";

grant references on table "public"."moduleConfiguration" to "service_role";

grant select on table "public"."moduleConfiguration" to "service_role";

grant trigger on table "public"."moduleConfiguration" to "service_role";

grant truncate on table "public"."moduleConfiguration" to "service_role";

grant update on table "public"."moduleConfiguration" to "service_role";


