import { MasterListValue } from "@prisma/client";

export const data: MasterListValue[] = [
    {
        id: "shghgh",
        masterListId: "shghgh",
        value: "1",
        displayName: "Display Name",
        description: "Description",
        sequence: 1,
        isActive: true,
        createdAt: new Date(),
        createdBy: "Created By",
        updatedAt: new Date(),
        lastUpdatedBy: "Updated By",
        syncToken: "Sync Token",
        deletedAt: null,
        deletedBy: null,
    },
    {
        id: "shghgh",
        masterListId: "shghgh",
        value: "1",
        displayName: "Display Name",
        description: "Description",
        sequence: 1,
        isActive: true,
        createdAt: new Date(),
        createdBy: "Created By",
        updatedAt: new Date(),
        lastUpdatedBy: "Updated By",
        syncToken: "Sync Token",
        deletedAt: null,
        deletedBy: null,
    },
    {
        id: "shghgdfdfdh",
        masterListId: "shghgh",
        value: "1",
        displayName: "Display Name",
        description: "Description",
        sequence: 1,
        isActive: true,
        createdAt: new Date(),
        createdBy: "Created By",
        updatedAt: new Date(),
        lastUpdatedBy: "Updated By",
        syncToken: "Sync Token",
        deletedAt: null,
        deletedBy: null,
    },
    {
        id: "shghghdfdf",
        masterListId: "shghgh",
        value: "1",
        displayName: "Display Name",
        description: "Description",
        sequence: 1,
        isActive: true,
        createdAt: new Date(),
        createdBy: "Created By",
        updatedAt: new Date(),
        lastUpdatedBy: "Updated By",
        syncToken: "Sync Token",
        deletedAt: null,
        deletedBy: null,
    }
]