export const List_Items = [
  {
    imageUrl: "/images/dynamics365.png",
    background: "#F2F1FD",
    name: "Dynamics 365 F&O",
    category_id: "Dynamics 365 F&O",
    description: "Lorem ipsum dolor sit amet set consectetur.",
    clientId: 1002024,
    clientSecret: "askdnkjasndvanrewvkjnedrvaner",
    resourceUrl: "http://loremipsum.dynamics.com",
    trigger: [
      {
        name: "Sales order is created",
        description: "When a sales order is created in my ERP",
        showSecondaryOptions: false,
        isDisabled: false,
        imageUrl: "/images/dynamics365.png",
        metadata: {},
      },
    ],
  },
  {
    imageUrl: "/images/businessCentral.svg",
    background: "#DEFDFF",
    name: "Business Central",
    category_id: "Business Central",
    description: "Lorem ipsum dolor sit amet set consectetur.",
    clientId: 1002025,
    clientSecret: "askdnkjasndvanrewvkjnedrvaner",
    resourceUrl: "http://loremipsum.business.com",
    trigger: [
      {
        name: "Get New Customer Info",
        description: "Event (Create)",
        from: "CustomerV2",
        imageUrl: "/images/businessCentral.svg",
        showSecondaryOptions: false,
        isDisabled: false,
        metadata: {},
      },
    ],
  },
  {
    imageUrl: "/images/businessCentral.svg",
    background: "#DEFD88",
    name: "Core Platform",
    category_id: "Core Platform",
    description: "Lorem ipsum dolor sit amet set consectetur.",
    clientId: 1002025,
    clientSecret: "askdnkjasndvanrewvkjnedrvaner",
    resourceUrl: "http://loremipsum.business.com",
    trigger: [
      {
        name: "Get New Customer Info",
        description: "Event (Create)",
        from: "CustomerV2",
        imageUrl: "/images/businessCentral.svg",
        showSecondaryOptions: false,
        isDisabled: false,
        metadata: {},
      },
    ],
  },
  {
    imageUrl: "/images/businessCentral.svg",
    background: "#DEFD88",
    name: "Sequential approval",
    category_id: "Core Platform",
    description: "Lorem ipsum dolor sit amet set consectetur.",
    clientId: 1002025,
    clientSecret: "askdnkjasndvanrewvkjnedrvaner",
    resourceUrl: "http://loremipsum.business.com",
    trigger: [
      {
        name: "Start approval process",
        description: "Event (Create)",
        from: "CustomerV2",
        imageUrl: "/images/businessCentral.svg",
        showSecondaryOptions: false,
        isDisabled: false,
        metadata: {},
      },
    ],
  },
  {
    imageUrl: "/images/businessCentral.svg",
    background: "#DEFD88",
    name: "Parallel approval",
    category_id: "Core Platform",
    description: "Lorem ipsum dolor sit amet set consectetur.",
    clientId: 1002025,
    clientSecret: "askdnkjasndvanrewvkjnedrvaner",
    resourceUrl: "http://loremipsum.business.com",
    trigger: [
      {
        name: "Start approval process",
        description: "Event (Create)",
        from: "CustomerV2",
        imageUrl: "/images/businessCentral.svg",
        showSecondaryOptions: false,
        isDisabled: false,
        metadata: {},
      },
    ],
  },
  {
    imageUrl: "/images/businessCentral.svg",
    background: "#DEFD88",
    name: "Schedule",
    category_id: "Schedule triggers",
    description: "Lorem ipsum dolor sit amet set consectetur.",
    clientId: 1002025,
    clientSecret: "askdnkjasndvanrewvkjnedrvaner",
    resourceUrl: "http://loremipsum.business.com",
    trigger: [],
  },
];
