import { DataTable } from '~/components/Globals/DataTable/DataTable'
import { columns } from '~/components/Globals/DataTable/Columns'

const data = [
    {
        id: "1",
        name: "Pfizer",
        code: "PF-07",
        url: "catalogapp.myprojectx.com",
        status: "inactive",
        users: 100,
        createdAt: "2024-08-24T02:55:00",
    },
    {
        id: "2",
        name: "Mark&co",
        code: "MNC",
        url: "getcirooles.myprojectx.com",
        status: "active",
        users: 80,
        createdAt: "2024-08-24T02:55:00",
    },
    {
        id: "3",
        name: "Johnson & Johnson",
        code: "JNJ",
        url: "jnj.myprojectx.com",
        status: "active",
        users: 150,
        createdAt: "2024-08-25T03:15:00",
    },
    {
        id: "4",
        name: "Novartis",
        code: "NVS",
        url: "novartis.myprojectx.com",
        status: "active",
        users: 120,
        createdAt: "2024-08-25T04:30:00",
    },
    {
        id: "5",
        name: "Roche",
        code: "ROG",
        url: "roche.myprojectx.com",
        status: "inactive",
        users: 90,
        createdAt: "2024-08-26T01:45:00",
    },
    {
        id: "6",
        name: "Merck",
        code: "MRK",
        url: "merck.myprojectx.com",
        status: "active",
        users: 110,
        createdAt: "2024-08-26T05:20:00",
    },
    {
        id: "7",
        name: "AstraZeneca",
        code: "AZN",
        url: "astrazeneca.myprojectx.com",
        status: "active",
        users: 130,
        createdAt: "2024-08-27T02:10:00",
    },
    {
        id: "8",
        name: "Abbott",
        code: "ABT",
        url: "abbott.myprojectx.com",
        status: "inactive",
        users: 70,
        createdAt: "2024-08-27T03:40:00",
    },
    {
        id: "9",
        name: "Bristol Myers Squibb",
        code: "BMS",
        url: "bms.myprojectx.com",
        status: "active",
        users: 140,
        createdAt: "2024-08-28T01:15:00",
    },
    {
        id: "10",
        name: "GlaxoSmithKline",
        code: "GSK",
        url: "gsk.myprojectx.com",
        status: "active",
        users: 160,
        createdAt: "2024-08-28T04:25:00",
    },
    {
        id: "11",
        name: "Eli Lilly",
        code: "LLY",
        url: "lilly.myprojectx.com",
        status: "active",
        users: 95,
        createdAt: "2024-08-29T02:30:00",
    },
    {
        id: "12",
        name: "Amgen",
        code: "AMGN",
        url: "amgen.myprojectx.com",
        status: "inactive",
        users: 85,
        createdAt: "2024-08-29T03:50:00",
    },
    {
        id: "13",
        name: "Gilead Sciences",
        code: "GILD",
        url: "gilead.myprojectx.com",
        status: "active",
        users: 105,
        createdAt: "2024-08-30T01:20:00",
    },
    {
        id: "14",
        name: "Biogen",
        code: "BIIB",
        url: "biogen.myprojectx.com",
        status: "active",
        users: 75,
        createdAt: "2024-08-30T04:15:00",
    },
    {
        id: "15",
        name: "Vertex",
        code: "VRTX",
        url: "vertex.myprojectx.com",
        status: "inactive",
        users: 65,
        createdAt: "2024-08-31T02:40:00",
    },
    {
        id: "16",
        name: "Regeneron",
        code: "REGN",
        url: "regeneron.myprojectx.com",
        status: "active",
        users: 115,
        createdAt: "2024-08-31T03:55:00",
    },
    {
        id: "17",
        name: "Moderna",
        code: "MRNA",
        url: "moderna.myprojectx.com",
        status: "active",
        users: 125,
        createdAt: "2024-09-01T01:30:00",
    },
    {
        id: "18",
        name: "BioNTech",
        code: "BNTX",
        url: "biontech.myprojectx.com",
        status: "active",
        users: 95,
        createdAt: "2024-09-01T04:20:00",
    },
    {
        id: "19",
        name: "Seagen",
        code: "SGEN",
        url: "seagen.myprojectx.com",
        status: "inactive",
        users: 55,
        createdAt: "2024-09-02T02:15:00",
    },
    {
        id: "20",
        name: "Horizon Therapeutics",
        code: "HZNP",
        url: "horizon.myprojectx.com",
        status: "active",
        users: 135,
        createdAt: "2024-09-02T03:45:00",
    }
] as const;

const TableDemo = () => {
    return <div className="container mx-auto py-10">
        <DataTable columns={columns} data={data} />
    </div>
}

export default TableDemo
