create table "public"."dynamicSalesOrder" (
    "id" bigint generated by default as identity not null,
    "data" jsonb,
    "customFields" JSONB,
    "createdBy" TEXT NOT NULL,
    "createdOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "modifiedBy" TEXT,
    "modifiedOn" TIMESTAMP WITH TIME ZONE,
    "deletedBy" TEXT,
    "deletedOn" TIMESTAMP WITH TIME ZONE
);


alter table "public"."dynamicSalesOrder" enable row level security;

CREATE UNIQUE INDEX "dynamicSalesOrder_pkey" ON public."dynamicSalesOrder" USING btree (id);

alter table "public"."dynamicSalesOrder" add constraint "dynamicSalesOrder_pkey" PRIMARY KEY using index "dynamicSalesOrder_pkey";

grant delete on table "public"."dynamicSalesOrder" to "anon";

grant insert on table "public"."dynamicSalesOrder" to "anon";

grant references on table "public"."dynamicSalesOrder" to "anon";

grant select on table "public"."dynamicSalesOrder" to "anon";

grant trigger on table "public"."dynamicSalesOrder" to "anon";

grant truncate on table "public"."dynamicSalesOrder" to "anon";

grant update on table "public"."dynamicSalesOrder" to "anon";

grant delete on table "public"."dynamicSalesOrder" to "authenticated";

grant insert on table "public"."dynamicSalesOrder" to "authenticated";

grant references on table "public"."dynamicSalesOrder" to "authenticated";

grant select on table "public"."dynamicSalesOrder" to "authenticated";

grant trigger on table "public"."dynamicSalesOrder" to "authenticated";

grant truncate on table "public"."dynamicSalesOrder" to "authenticated";

grant update on table "public"."dynamicSalesOrder" to "authenticated";

grant delete on table "public"."dynamicSalesOrder" to "service_role";

grant insert on table "public"."dynamicSalesOrder" to "service_role";

grant references on table "public"."dynamicSalesOrder" to "service_role";

grant select on table "public"."dynamicSalesOrder" to "service_role";

grant trigger on table "public"."dynamicSalesOrder" to "service_role";

grant truncate on table "public"."dynamicSalesOrder" to "service_role";

grant update on table "public"."dynamicSalesOrder" to "service_role";